# Configuración para Gemini con LangChain4j
# OJO: Quitamos los ${} para que lea el texto directo
langchain4j.google-ai-gemini.api-key=AIzaSyDtOoPplbkHQi9CGsYZ1nHSV7tdLDbm6zs
langchain4j.google-ai-gemini.model-name=gemini-2.5-flash
langchain4j.google-ai-gemini.log-requests=true
langchain4j.google-ai-gemini.log-responses=true

# Configuración de la base de datos
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true